# Generated by Django 5.0.2 on 2024-09-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leisure_activities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leisureactivity',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useractivitypreference',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
