# Generated by Django 5.0.2 on 2024-08-29 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultural_places', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturalplace',
            name='opening_hours',
        ),
    ]
