# Generated by Django 5.0.2 on 2024-08-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultural_places', '0003_remove_culturalplace_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalplace',
            name='opening_hours',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
