# Generated by Django 5.0.2 on 2024-09-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultural_places', '0005_alter_culturalplace_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalplace',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userplacepreference',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
