# Generated by Django 5.0.2 on 2024-03-05 05:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalPlace',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('opening_hours', models.DateTimeField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cultural_places')),
            ],
            options={
                'verbose_name': 'Cultural Place',
                'verbose_name_plural': 'Cultural Places',
                'db_table': 'cultural_place',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserPlacePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'User Place Preference',
                'verbose_name_plural': 'User Place Preferences',
                'db_table': 'user_place_preference',
                'managed': True,
            },
        ),
    ]
