# Generated by Django 5.0.2 on 2024-03-05 05:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Activity Category',
                'verbose_name_plural': 'Activity Categories',
                'db_table': 'activity_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LeisureActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='leisure_activities')),
            ],
            options={
                'verbose_name': 'Leisure Activity',
                'verbose_name_plural': 'Leisure Activities',
                'db_table': 'leisure_activity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserActivityPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'User Activity Preference',
                'verbose_name_plural': 'User Activity Preferences',
                'db_table': 'user_activity_preference',
                'managed': True,
            },
        ),
    ]
